spring:
  config:
    activate:
      on-profile: local
file:
  blacklist:
    path: ./src/main/resources/customer_blacklist.csv

---
spring:
  config:
    activate:
      on-profile: file

file:
  voucher:
    path: ./src/main/resources/voucher_list.csv
  blacklist:
    path: ./src/main/resources/customer_blacklist.csv

---
spring:
  config:
    activate:
      on-profile: jdbc

